config/routes.rb
Rails.application.routes.draw do
  get 'store/index'

  resources :line_items
  resources :carts
  get 'items/index'
  resources :items

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  validates :name, :price, :description, :img_url , presence: true
  validates :price,numericality:{ greater_than_or_equal_to: 1 }
  validates :img_url, allow_blank: true, format: {
  with: %r{\.(gif|jpg|png)\Z}i,
  message: 'must be a URL for GIF, JPG or PNG image.'
  }
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :cart
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :edit, :update, :destroy]

  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy
    respond_to do |format|
      format.html { redirect_to carts_url, notice: 'Cart was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params.fetch(:cart, {})
    end
end

app/controllers/concerns/current_cart.rb
module CurrentCart
  private
    def set_cart
      @cart = Cart.find(session[:cart_id])
    rescue ActiveRecord::RecordNotFound
      @cart = Cart.create
      session[:cart_id] = @cart.id
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items =Item.all
  end
  def new
    @item = Item.new
    @items = Item.all
  end
  def create
    binding.pry
    @item = Item.new(item_params)
    if @item.save
      redirect_to :action => "index"
    else
      render :action => "new"
    end
  end
  def item_params
    params.require(:item).permit(:name, :price, :description, :img_url)
  end
  def edit
    @item = Item.find(params[:id])
  end
  def update
    @item =Item.find(params[:id])
    @item.update_attributes(params.require(:item).permit(:name, :price, :description, :img_url))
    if @item.save
      redirect_to :action => "index"
    else
      render :action => "edit"
    end
  end
  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    flash[:notice] = 'deleted'
    redirect_to :action => 'index'
  end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  before_action :set_line_item, only: [:show, :edit, :update, :destroy]

  include CurrentCart
  before_action :set_cart,only: [:create]
  before_action :set_line_item, only: [:show, :edit, :update, :destroy]

  # GET /line_items
  # GET /line_items.json
  def index
    @line_items = LineItem.all
  end

  # GET /line_items/1
  # GET /line_items/1.json
  def show
  end

  # GET /line_items/new
  def new
    @line_item = LineItem.new
  end

  # GET /line_items/1/edit
  def edit
  end

  # POST /line_items
  # POST /line_items.json
  def create
    @line_item = LineItem.new(line_item_params)

    respond_to do |format|
      if @line_item.save
        format.html { redirect_to @line_item, notice: 'Line item was successfully created.' }
        format.json { render :show, status: :created, location: @line_item }
      else
        format.html { render :new }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /line_items/1
  # PATCH/PUT /line_items/1.json
  def update
    respond_to do |format|
      if @line_item.update(line_item_params)
        format.html { redirect_to @line_item, notice: 'Line item was successfully updated.' }
        format.json { render :show, status: :ok, location: @line_item }
      else
        format.html { render :edit }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /line_items/1
  # DELETE /line_items/1.json
  def destroy
    @line_item.destroy
    respond_to do |format|
      format.html { redirect_to line_items_url, notice: 'Line item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_line_item
      @line_item = LineItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def line_item_params
      params.require(:line_item).permit(:item_id, :cart_id)
    end
end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
  def operations_on_item(item)
    links = []
    links << link_to('edit',[ :edit, item ])
    links << link_to('complete','#')
    links << link_to('delete',item, :method => :delete,:confirm => 'do u realy wanna delete this one?')
    links.join(' | ')
  end
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/views/carts/_form.html.erb
<%= form_with(model: cart, local: true) do |form| %>
  <% if cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% cart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Carts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_cart_path(@cart) %> |
<%= link_to 'Back', carts_path %>

app/views/items/_form.html.erb
<%= form_for item do |f| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count,"error") %>
        prohibited item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |massage| %>
        <li><%= massage %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>
  <div class="description">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>
  <div class="filed">
    <%= f.label :img_url %>
    <%= f.text_field :img_url %>
  </div>
  <div class="actions">
    <%= f.submit "submit" %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1> Update your profile</h1>

<%= form_for @item,:url=>{:action => 'update', :id => @item} do |form| %>

  <div>Name:<%= form.text_field :name %></div>
  <div>Price:<%= form.text_field :price %></div>
  <div>Description:<%= form.text_area :description %></div>
  <div>Url:<%= form.text_field :img_url %></div>
  <%= form.submit 'update' %>
<% end %>
<%= link_to "back", items_index_path %>

app/views/items/index.html.erb
<!DOCTYPE html>
<head>
    <title>test</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="/css/bootstrap.min.css" />
    <link rel="stylesheet" href="/css/general.css" />

    <script type="text/javascript" src="/js/jquery.min.js"></script>
    <script type="text/javascript" src="/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="/js/app.js"></script>
</head>
<body>

<!-- ヘッダー部 -->
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
        <div class="nav-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">top</a>
        </div><!-- nav-header -->
        <div id="navbar" class="navbar-collapse collapse in" area-expanded="true">
            <ul class="nav navbar-nav navbar-right">
                <li><a href="">info</a></li>
                <li><a href="">contact us</a></li>
                <li><a href="">about us</a></li>
            </ul>
            <form class="navbar-form navbar-right">
                <input type="text" class="form-control" placeholder="search">
            </form>
        </div><!-- navbar -->
    </div><!-- container-fluid -->
</nav>

<div class="container-fluid don_hidden">
  <div class="row">
    <div class="col-sm-3 col-md-2 sidebar don_hidden"><!--sidebar-->
      <ul class="nav nav-sidebar">
        <%= render :partial => "./layouts/sidebar" %>
      </ul>
    </div>
    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2">
      <!-- main contents -->
      <h1 class="text-success">Don miss these good servants!</h1>
      <div class="row">
        <% @items.each do |item| %>
            <% if File.exist?('./app/assets/images/'+item.img_url) %>
    <!--there are -->
              <img><%= image_tag item.img_url, :size =>'114x196' %></img>
              <div>Name:<%= item.name %></div>
              <div>Price:<%= item.price %></div>
              <div>What did (s)he do:<%= item.description %></div>
              <div><%= link_to("edit", :action => 'edit', :id =>item.id) %></div>
              <div><%= link_to 'Destroy',item, method: :delete,data: { confirm: 'do u really wanna delete this one?'}%></div>
              <div><%= link_to 'add to cart',{:controller => 'line_items',:action => "new",item_id: item.id} %></div>
              <div class="clear"></div>
            <% else %>
    <!-- there arent -->
              <img><%= image_tag 'none.png', :size =>'120x120' %></img>
              <div>Name:<%= item.name %></div>
              <div>Price:<%= item.price %></div>
              <div>What did (s)he do:<%= item.description %></div>
              <div><%= link_to("edit", :action => 'edit', :id =>item.id) %></div>
              <div><%= link_to 'Destroy',item, method: :delete,data: { confirm: 'do u really wanna delete this one?'}%></div>
              <div class="clear"></div>
            <%end%><!--if end -->
        <% end %><!--each do end -->
      </div>
      check
    </div><!--main end-->
  </div>
</div><!-- container-fluid -->
<div class="clear"></div>
<div class="container-fluid footer">
    <div class="row">
      <%= render :partial => "./layouts/footer" %>
    </div>
</div>

</body>
</html>

app/views/items/new.html.erb
<h1>Item Register</h1>

<%= render 'form', item: @item %>
<%= link_to 'back',items_index_path %>

app/views/layouts/_footer.html.erb
<%= d = Date.today %>
<%= str = d.strftime("%Y年 %m月 %d日") %>
<div>Currently,Limited Pick UP is ....</div>
<div><%= print(str) %></div>

app/views/layouts/_index_none.html.erb
<img><%= image_tag 'none.png', :size =>'120x120' %></img>
<div>Name:<%= item.name %></div>
<div>Price:<%= item.price %></div>
<div>What did (s)he do:<%= item.description %></div>
<div><%= link_to("edit", :action => 'edit', :id =>item.id) %></div>
<div><%= link_to 'Destroy',item, method: :delete,data: { confirm: 'do u really wanna delete this one?'}%></div>
<div class="clear"></div>

app/views/layouts/_noimage.html.erb
<img><%= image_tag 'none.png', :size =>'120x120' %></img>
<div>Name:<%= item.name %></div>
<div>Price:<%= item.price %></div>
<div>What did (s)he do:<%= item.description %></div>
<div><%= link_to("edit", :action => 'edit', :id =>item.id) %></div>
<div><%= link_to 'Destroy',item, method: :delete,data: { confirm: 'do u really wanna delete this one?'}%></div>
<div class="clear"></div>

app/views/layouts/_sidebar.html.erb
<li class="active">Menu Sidebar</li>
<li><a href="">home</a></li>
<li><a href="">by class</a></li>
<li><a href="">by sex</a></li>
<li><a href="">by role</a></li>
<li>by stars</li>
  <li><a href="">5stars</a></li>
  <li><a href="">4stars</a></li>
  <li><a href="">3stars</a></li>
  <li><a href="">2stars</a></li>
  <li><a href="">1star</a></li>
<li>by GATYA</li>
<li><a href="">constant GATYA</a></li>
<li><a href="">limited GATYA</a></li>
<li><a href="">friend GATYA</a></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RoR</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/line_items/_form.html.erb
<%= form_with(model: line_item, local: true) do |form| %>
  <% if line_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(line_item.errors.count, "error") %> prohibited this line_item from being saved:</h2>

      <ul>
      <% line_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :item_id %>
    <%= form.text_field :item_id, id: :line_item_item %>
  </div>

  <div class="field">
    <%= form.label :cart_id %>
    <%= form.text_field :cart_id, id: :line_item_cart_id %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/line_items/edit.html.erb
<h1>Editing Line Item</h1>

<%= render 'form', line_item: @line_item %>

<%= link_to 'Show', @line_item %> |
<%= link_to 'Back', line_items_path %>

app/views/line_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Line Items</h1>

<table>
  <thead>
    <tr>
      <th>Item</th>
      <th>Cart</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @line_items.each do |line_item| %>
      <tr>
        <td><%= line_item.item_id %></td>
        <td><%= line_item.cart_id %></td>
        <td><%= link_to 'Show', line_item %></td>
        <td><%= link_to 'Edit', edit_line_item_path(line_item) %></td>
        <td><%= link_to 'Destroy', line_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Line Item', new_line_item_path %>

app/views/line_items/new.html.erb
<h1>New Line Item</h1>

<%= render 'form', line_item: @line_item %>

<%= link_to 'Back', line_items_path %>

app/views/line_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Item:</strong>
  <%= @line_item.item_id %>
</p>

<p>
  <strong>Cart:</strong>
  <%= @line_item.cart_id %>
</p>

<%= link_to 'Edit', edit_line_item_path(@line_item) %> |
<%= link_to 'Back', line_items_path %>

app/views/store/index.html.erb
<h1>Store#index</h1>
<p>Find me in app/views/store/index.html.erb</p>